stages:
  - build_and_push
  - deploy

variables:
  AWS_DEFAULT_REGION: 'us-east-1'
  ECR_REPO: '784434436921.dkr.ecr.us-east-1.amazonaws.com/fastapi-app'
  IMAGE_TAG: 'latest'
  DOCKER_HOST: 'tcp://docker:2375/'
  DOCKER_TLS_CERTDIR: ''

build_and_push:
  stage: build_and_push
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add --no-cache python3 py3-pip curl docker aws-cli
    - aws --version
    - echo "Logging in to AWS ECR"
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPO
  script:
    - echo "Building Docker image"
    - docker build -t fastapi-app .
    - docker tag fastapi-app:latest $ECR_REPO:$IMAGE_TAG
    - echo "Pushing Docker image to ECR"
    - docker push $ECR_REPO:$IMAGE_TAG

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache python3 py3-pip curl terraform aws-cli
  script:
    - echo "Deploying infrastructure using Terraform"
    - cd terraform
    - terraform init
    - terraform apply -auto-approve
    - echo "Forcing ECS to use updated image"
    - aws ecs update-service --cluster fastapi-cluster --service fastapi-service --force-new-deployment --region $AWS_DEFAULT_REGION
