stages:
  - build
  - push
  - deploy

variables:
  AWS_DEFAULT_REGION: 'us-east-1'
  ECR_REPO: '784434436921.dkr.ecr.us-east-1.amazonaws.com/fastapi-app'
  IMAGE_TAG: 'latest'
  DOCKER_HOST: 'tcp://docker:2375/'
  DOCKER_TLS_CERTDIR: ''

before_script:
  - apk add --no-cache python3 py3-pip curl docker aws-cli
  - aws --version
  - echo "Logging in to AWS ECR"
  - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPO

build_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Building Docker image"
    - docker build -t fastapi-app .
    - docker tag fastapi-app:latest $ECR_REPO:$IMAGE_TAG

push_image:
  stage: push
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Pushing Docker image to ECR"
    - docker push $ECR_REPO:$IMAGE_TAG

deploy:
  stage: deploy
  image: hashicorp/terraform:light
  before_script:
    - apk add --no-cache python3 py3-pip curl aws-cli
  script:
    - echo "Deploying with Terraform"
    - cd terraform
    - terraform init
    - terraform apply -auto-approve
    - aws ecs update-service --cluster fastapi-cluster --service fastapi-service --force-new-deployment --region $AWS_DEFAULT_REGION
